### PR TITLE
Expand gmq.AsTime to support DATE and TIME types

### PR DESCRIPTION
**Pull request by pouyanh**
Signed-off-by: Pouyan Heyratpour <pouyan@cloudzero.ir>

### CODE REVIEW

**Comment by mijia** [comment]
Thank you very much.

**Comment by pouyanh** [comment]
I'm planning to add **Join** feature. Do you have any considerations or notes about which point I should start at and what things should I care about @mijia ?

**Comment by mijia** [comment]
@pouyanh Great news, really thank you for that. I lost focus on this project for a long time and haven't thought this through. Don't know if there would be some better solution if we insist on no reflection used. Maybe we need to work this out depends on the runtime reflection for the `Join` or `Union`.

**Comment by mijia** [comment]
Currently I am using `modelq` to generate the basic models , but using `sqlx` for the complicated query such as the join, union and etc.

**Pull request merged**
